header_file = "./header.txt"
footer_file = "./footer.txt"

[defs]
BL          = "#000000"
WH          = "#0A151F"

[mods]
Xft.dpi     = "DPI"

[mods.col]
bl          = "BL"
wh          = "WH"

[mods.ALL]
background  = "#0D1017"
foreground  = "#F1F7ED"
color0      = "#252550"
color1      = "#D7263D"
color2      = "#B0DB43"
color3      = "#FFAE03"
